### ISSUE TITLE
Coin Type - LTC ! LBTC

### ISSUE THREAD

**Issue by java4tech** [ConsensusJ/wallet-framework#4]
BipStandardKeyChainGroupStructure.java

private static ChildNumber COINTYPE_LBTC = new ChildNumber(2, true);
 
As per https://github.com/satoshilabs/slips/blob/master/slip-0044.md

Index 2 is reserved for LTC not LBTC

**Comment by msgilligan** [comment]
`LBTC` was a typo, thanks for pointing it out!

**Comment by msgilligan** [comment]
Fixed in 3d073cde41c80e3b976b1a1f557186ccc9a6440d
